FROM python:3.11

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PORT "PORT"
ENV DB_URI "DB_URI"
ENV SMTP_HOST "SMTP_HOST"
ENV SMTP_PORT "SMTP_PORT"
ENV SMTP_LOGIN "SMTP_LOGIN"
ENV SMTP_PASSWORD "SMTP_PASSWORD"
ENV SMTP_EMAIL "SMTP_EMAIL"
ENV SMTP_NAME "SMTP_NAME"

CMD ["python", "server.py"]
